// Custom Worker entrypoint.
//
// OpenNext generates `.open-next/worker.js`, which only exports a `fetch`
// handler. Our `wrangler.jsonc` also declares cron triggers, and Cloudflare invokes them
// through a `scheduled()` handler. Because the generated worker has no
// `scheduled()` export, every cron tick failed with "Handler does not
// export a scheduled() function".
//
// This wrapper re-exports OpenNext's `fetch` unchanged and adds a `scheduled()`
// handler that re-dispatches each cron job back through the same in-process
// Next.js handler, so the existing `/api/cron/*` routes keep owning the logic.
// `wrangler.jsonc` `main` points here instead of at `.open-next/worker.js`.

import { WorkerEntrypoint } from 'cloudflare:workers';
// `.open-next/worker.js` is generated by the OpenNext build, so whether this
// import resolves depends on whether anyone has built recently: it never exists
// in CI (which typechecks before it builds) and usually does exist locally after
// `npm run preview` or `npm run deploy`.
//
// The suppression below is the permissive kind on purpose. With `allowJs` on, a
// worker.js that *is* present makes this import resolve cleanly, and the strict
// "expect error" form then fails as an unused directive (TS2578) — turning a
// successful local build into a failing pre-commit until `.open-next` is
// deleted. The permissive form is correct whether or not the build output
// exists. (Don't name the strict directive in these comments: TypeScript treats
// any comment containing it as a real directive.)
// biome-ignore lint/suspicious/noTsIgnore: the strict directive is exactly what breaks here — see above
// @ts-ignore
import { default as handler } from './.open-next/worker.js';
import {
  type CronJob,
  isOffloadedCronPath,
  jobsForTick,
  mergeRelayedSecrets,
  pickJobSecrets,
  type RoleEnv,
  workerRole,
} from './lib/cronSchedule';

/**
 * RPC entrypoint on the site Worker that hands the jobs Worker its secrets
 * (JOB_SECRET_NAMES only). Named entrypoints are reachable solely through a
 * service binding inside this Cloudflare account; it has no fetch handler and
 * no URL. This exists because Cloudflare never returns secret values, so a
 * second Worker otherwise needs every value re-entered by hand.
 */
export class SecretRelay extends WorkerEntrypoint<CloudflareEnv> {
  async jobSecrets(): Promise<Record<string, string>> {
    // Only the Worker that actually holds the secrets serves them.
    if (workerRole(this.env) === 'jobs') return {};
    return pickJobSecrets(this.env);
  }
}

/** Relayed secrets are re-fetched at most this often per isolate (picks up rotations). */
const RELAY_TTL_MS = 10 * 60 * 1000;
let relayed: { at: number; values: Record<string, string> } | null = null;

/**
 * On the jobs Worker, `env` with any job secret it lacks filled in from the
 * site over SITE_SECRETS. Passed to OpenNext as the request env, so routes see
 * them through both getCloudflareContext().env and process.env.
 */
async function withRelayedSecrets(env: CloudflareEnv): Promise<CloudflareEnv> {
  const relay = (env as unknown as RoleEnv).SITE_SECRETS;
  if (workerRole(env) !== 'jobs' || !relay) return env;
  if (!relayed || Date.now() - relayed.at > RELAY_TTL_MS) {
    try {
      relayed = { at: Date.now(), values: await relay.jobSecrets() };
    } catch (error) {
      // Keep using the last good copy; with none, run on the Worker's own secrets.
      console.error(
        '[secret-relay] fetching job secrets from the site failed',
        error,
      );
      if (!relayed) return env;
    }
  }
  return mergeRelayedSecrets(env, relayed.values);
}

async function runCronJob(
  job: CronJob,
  env: CloudflareEnv,
  ctx: ExecutionContext,
): Promise<void> {
  // Secrets live on the runtime env even though they aren't in the generated
  // `CloudflareEnv` type (same values the routes read via `process.env`).
  // Falls back to ADMIN_SECRET so a Worker that hasn't had CRON_SECRET set yet
  // keeps dispatching instead of silently skipping every job.
  const runtimeEnv = env as unknown as Record<string, string | undefined>;
  const secret = runtimeEnv[job.secretVar] || runtimeEnv.ADMIN_SECRET;
  if (!secret) {
    console.error(
      `[cron] Skipping ${job.path}: neither ${job.secretVar} nor ADMIN_SECRET is configured`,
    );
    return;
  }

  const request = new Request(`https://allmcps.com${job.path}`, {
    method: 'POST',
    headers: { authorization: `Bearer ${secret}` },
  });

  // On the split deployment the site schedules and the jobs Worker executes:
  // hand the job over the JOBS binding so its memory/CPU lands in that isolate.
  const jobs = (env as unknown as RoleEnv).JOBS;
  const offload =
    workerRole(env) === 'site' && jobs && isOffloadedCronPath(job.path);

  try {
    const response = offload
      ? await jobs.fetch(request)
      : await handler.fetch(request, env, ctx);
    // Always read the body: an unread response from the JOBS binding shows up
    // as a "canceled" invocation on the jobs Worker, and the routes' summary
    // line (e.g. ai-content's "enriched N … failed M") is the only per-run
    // record of what a job did.
    const body = await response.text().catch(() => '');
    if (!response.ok) {
      console.error(
        `[cron] ${job.path} responded ${response.status}: ${body.slice(0, 500)}`,
      );
    } else {
      let summary = '';
      try {
        const parsed = JSON.parse(body) as { message?: unknown };
        if (typeof parsed.message === 'string') summary = `: ${parsed.message}`;
      } catch {
        // Not JSON; the status alone is enough.
      }
      console.log(
        `[cron] ${job.path} ok (${response.status})${summary.slice(0, 400)}`,
      );
    }
  } catch (error) {
    console.error(`[cron] ${job.path} threw`, error);
  }
}

export default {
  async fetch(request, env, ctx) {
    const role = workerRole(env);
    const { hostname, pathname } = new URL(request.url);
    // The jobs Worker has no public routes, so this only turns away stray
    // requests. It never 404s allmcps.com itself: if the jobs config ever lands
    // on the site Worker (as a Workers Builds name override once nearly did),
    // the site keeps serving rather than going dark.
    if (
      role === 'jobs' &&
      !pathname.startsWith('/api/cron/') &&
      hostname !== 'allmcps.com' &&
      hostname !== 'www.allmcps.com'
    ) {
      return new Response('Not found', { status: 404 });
    }
    const jobs = (env as unknown as RoleEnv).JOBS;
    if (role === 'site' && jobs && isOffloadedCronPath(pathname)) {
      return jobs.fetch(request);
    }
    return handler.fetch(request, await withRelayedSecrets(env), ctx);
  },

  async scheduled(
    controller: ScheduledController,
    env: CloudflareEnv,
    ctx: ExecutionContext,
  ): Promise<void> {
    const now = new Date(controller.scheduledTime);

    // `controller.cron` is the pattern (from wrangler.jsonc) that fired this
    // tick, so each schedule only runs its own job list — otherwise overlapping
    // patterns would double-run jobs.
    const jobs = jobsForTick(controller.cron, workerRole(env));
    const jobEnv = jobs.length > 0 ? await withRelayedSecrets(env) : env;

    // Run sequentially so overlapping D1 writes / third-party rate limits stay
    // predictable, and so one failing job never blocks the others.
    for (const job of jobs) {
      if (job.shouldRun && !job.shouldRun(now)) continue;
      await runCronJob(job, jobEnv, ctx);
    }
  },
} satisfies ExportedHandler<CloudflareEnv>;
