// Custom Worker entrypoint.
//
// OpenNext generates `.open-next/worker.js`, which only exports a `fetch`
// handler. Our `wrangler.jsonc` also declares cron triggers, and Cloudflare invokes them
// through a `scheduled()` handler. Because the generated worker has no
// `scheduled()` export, every cron tick failed with "Handler does not
// export a scheduled() function".
//
// This wrapper re-exports OpenNext's `fetch` unchanged and adds a `scheduled()`
// handler that re-dispatches each cron job back through the same in-process
// Next.js handler, so the existing `/api/cron/*` routes keep owning the logic.
// `wrangler.jsonc` `main` points here instead of at `.open-next/worker.js`.

// `.open-next/worker.js` is generated by the OpenNext build, so whether this
// import resolves depends on whether anyone has built recently: it never exists
// in CI (which typechecks before it builds) and usually does exist locally after
// `npm run preview` or `npm run deploy`.
//
// The suppression below is the permissive kind on purpose. With `allowJs` on, a
// worker.js that *is* present makes this import resolve cleanly, and the strict
// "expect error" form then fails as an unused directive (TS2578) — turning a
// successful local build into a failing pre-commit until `.open-next` is
// deleted. The permissive form is correct whether or not the build output
// exists. (Don't name the strict directive in these comments: TypeScript treats
// any comment containing it as a real directive.)
// biome-ignore lint/suspicious/noTsIgnore: the strict directive is exactly what breaks here — see above
// @ts-ignore
import { default as handler } from './.open-next/worker.js';
import {
  type CronJob,
  isOffloadedCronPath,
  jobsForTick,
  type RoleEnv,
  workerRole,
} from './lib/cronSchedule';

async function runCronJob(
  job: CronJob,
  env: CloudflareEnv,
  ctx: ExecutionContext,
): Promise<void> {
  // Secrets live on the runtime env even though they aren't in the generated
  // `CloudflareEnv` type (same values the routes read via `process.env`).
  // Falls back to ADMIN_SECRET so a Worker that hasn't had CRON_SECRET set yet
  // keeps dispatching instead of silently skipping every job.
  const runtimeEnv = env as unknown as Record<string, string | undefined>;
  const secret = runtimeEnv[job.secretVar] || runtimeEnv.ADMIN_SECRET;
  if (!secret) {
    console.error(
      `[cron] Skipping ${job.path}: neither ${job.secretVar} nor ADMIN_SECRET is configured`,
    );
    return;
  }

  const request = new Request(`https://allmcps.com${job.path}`, {
    method: 'POST',
    headers: { authorization: `Bearer ${secret}` },
  });

  try {
    const response = await handler.fetch(request, env, ctx);
    if (!response.ok) {
      const body = await response.text().catch(() => '');
      console.error(
        `[cron] ${job.path} responded ${response.status}: ${body.slice(0, 500)}`,
      );
    } else {
      console.log(`[cron] ${job.path} ok (${response.status})`);
    }
  } catch (error) {
    console.error(`[cron] ${job.path} threw`, error);
  }
}

export default {
  async fetch(request, env, ctx) {
    const role = workerRole(env);
    const { pathname } = new URL(request.url);
    if (role === 'jobs' && !pathname.startsWith('/api/cron/')) {
      return new Response('Not found', { status: 404 });
    }
    const jobs = (env as unknown as RoleEnv).JOBS;
    if (role === 'site' && jobs && isOffloadedCronPath(pathname)) {
      return jobs.fetch(request);
    }
    return handler.fetch(request, env, ctx);
  },

  async scheduled(
    controller: ScheduledController,
    env: CloudflareEnv,
    ctx: ExecutionContext,
  ): Promise<void> {
    const now = new Date(controller.scheduledTime);

    // `controller.cron` is the pattern (from wrangler.jsonc) that fired this
    // tick, so each schedule only runs its own job list — otherwise overlapping
    // patterns would double-run jobs.
    const jobs = jobsForTick(controller.cron, workerRole(env));

    // Run sequentially so overlapping D1 writes / third-party rate limits stay
    // predictable, and so one failing job never blocks the others.
    for (const job of jobs) {
      if (job.shouldRun && !job.shouldRun(now)) continue;
      await runCronJob(job, env, ctx);
    }
  },
} satisfies ExportedHandler<CloudflareEnv>;
