UPDATE servers SET category = '🖥️ OS Automation' WHERE id = 'agenticempire-axint';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'aidemd-mcp-server';
UPDATE servers SET category = '🖥️ OS Automation' WHERE id = 'andrewschreiber-desktopinsights-mcp';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'callstackincubator-agent-device';
UPDATE servers SET category = '🖥️ OS Automation' WHERE id = 'carloshpdoc-memorydetective';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'daghis-teamcity-mcp';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'danmat-create-packkit';
UPDATE servers SET category = '🔗 Aggregators' WHERE id = 'delimit-ai-delimit';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'deploy-mcp-deploy-mcp';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'ellmos-ai-ellmos-codecommander-mcp';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'explorer-64-imagcon-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'eyaushev-swagger-testcase-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'fantasieleven-code-callout';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'hyperb1iss-droidmind';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'idosal-git-mcp';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'jarvisassistantux-loopsense';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'jetbrains-mcpproxy';
UPDATE servers SET category = '🖥️ OS Automation' WHERE id = 'jktfe-servemyapi';
UPDATE servers SET category = '🖥️ OS Automation' WHERE id = 'kapeli-dash-mcp-server';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'ladislavsopko-mcp-ai-server-visual-studio';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'lumabyteco-clarifyprompt-mcp';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'meanands-npm-package-docs-mcp';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'mikhailhal-ariadne';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'mikusnuz-app-publish-mcp';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'mobilereality-mdma';
UPDATE servers SET category = '🔗 Aggregators' WHERE id = 'neo1228-spring-boot-starter-swagger-mcp';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'neverlow512-agent-droid-bridge';
UPDATE servers SET category = '🔒 Security' WHERE id = 'ofershap-mcp-server-devutils';
UPDATE servers SET category = '🔒 Security' WHERE id = 'ofershap-mcp-server-dns';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'ofershap-mcp-server-github-actions';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'ofershap-mcp-server-github-gist';
UPDATE servers SET category = '🔒 Security' WHERE id = 'optimaquantum-claude-critical-rules-mcp';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'paramount-engineering-roku-dev-studio';
UPDATE servers SET category = '📂 File Systems' WHERE id = 'paulhkang94-markview';
UPDATE servers SET category = '📊 Data Platforms' WHERE id = 'posthog-mcp';
UPDATE servers SET category = '🖥️ OS Automation' WHERE id = 'pratyay-mac-monitor-mcp';
UPDATE servers SET category = '👨‍💻 Code Execution' WHERE id = 'promptexecution-just-mcp';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'qainsights-jmeter-mcp-server';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'qainsights-locust-mcp-server';
UPDATE servers SET category = '🔒 Security' WHERE id = 'rabdulsal-appstore-release-mcp';
UPDATE servers SET category = '🔗 Aggregators' WHERE id = 'reapi-com-mcp-openapi';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'repowise-dev-repowise';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'richer-richard-fenestra';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'ronantakizawa-a11ymcp';
UPDATE servers SET category = '🎧 Support & Service Management' WHERE id = 'rootly-ai-labs-rootly-mcp-server';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'ryan0204-github-repo-mcp';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'saranshbamania-mobile-device-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'saurav61091-mcp-openapi';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'sequa-ai-sequa-mcp';
UPDATE servers SET category = '🔗 Aggregators' WHERE id = 'snaggle-ai-openapi-mcp-server';
UPDATE servers SET category = '🔗 Aggregators' WHERE id = 'specshield26-specshield-mcp-server';
UPDATE servers SET category = '🔒 Security' WHERE id = 'tatavarthitarun-nowsecure-mcp-server';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'thecombatwombat-replicant-mcp';
UPDATE servers SET category = '🖥️ OS Automation' WHERE id = 'utensils-mcp-nixos';
UPDATE servers SET category = '🔗 Aggregators' WHERE id = 'ycs77-apifable';
UPDATE servers SET category = '🔗 Aggregators' WHERE id = 'zaizaizhao-mcp-swagger-server';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'zenml-io-mcp-zenml';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'zillow-auto-mobile';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'hood-hood-name-service';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'goji';
UPDATE servers SET category = '🔒 Security' WHERE id = 'pre-trip-compliance-scanner';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'trading';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'beauty';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'google-ads';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'agentberg';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'agentic-news';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'puroair';
UPDATE servers SET category = '🔬 Research' WHERE id = 'ai-advisors';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'mcp-2';
UPDATE servers SET category = '🔒 Security' WHERE id = 'arketo';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'supershopping';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'health';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'bizmuse-ai-music-video';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'bloopo-make-ads';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'bloopo-ai-ad-creative-studio';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'buron';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'cabrini-market-data';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'can-i-vibe-ai-coding-provider-status';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'canvora';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'canvora-2';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'ccapi';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'china-marketing-ai-intelligence-mcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'china-marketing-ai-intelligence-mcp-2';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'cirra-ai-salesforce-admin-mcp-server';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'cirra-ai-salesforce-admin-mcp-server-2';
UPDATE servers SET category = '🔒 Security' WHERE id = 'clarid-compliance';
UPDATE servers SET category = '🔗 Aggregators' WHERE id = 'hapi-mcp-server';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'compeller';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'compeller-2';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'creationloop';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'cueframe';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'd50-ai-sales-marketing-hiring-automation';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'dealfilter';
UPDATE servers SET category = '🔒 Security' WHERE id = 'tailscale-rmcp-2';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'tvwizard';
UPDATE servers SET category = '🔬 Research' WHERE id = 'docuguru';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'dynamic-feed';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'filtrix-ai-mcp';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'gemus';
UPDATE servers SET category = '🔒 Security' WHERE id = 'vet';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'insideralpha-sec-insider-trading';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'ironscout';
UPDATE servers SET category = '🔒 Security' WHERE id = 'agent-sec';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'kive';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'mcp-1786400436218';
UPDATE servers SET category = '🎓 Education' WHERE id = 'llamanotes';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'llm-hosting-pricing';
UPDATE servers SET category = '🔬 Research' WHERE id = 'mlp-tax-computation-engine';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'marketcore';
UPDATE servers SET category = '🔒 Security' WHERE id = 'masnavi';
UPDATE servers SET category = '🔬 Research' WHERE id = 'lens';
UPDATE servers SET category = '🔬 Research' WHERE id = 'lens-2';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'nashboard-merchants';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'brand-intelligence';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'openarx';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'monitoring';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'opinly';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'outlit';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'pipe2-ai';
UPDATE servers SET category = '🔒 Security' WHERE id = 'preclick-an-mcp-native-url-preflight-scanning-service-for-autonomous-agents';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'mcp-20';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'mcp-21';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'quantifyme';
UPDATE servers SET category = '🔬 Research' WHERE id = 'refd';
UPDATE servers SET category = '🔒 Security' WHERE id = 'rail-score';
UPDATE servers SET category = '🔒 Security' WHERE id = 'retro-diffusion-pixel-art';
UPDATE servers SET category = '🔒 Security' WHERE id = 'rfp-ai';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcp-25';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'searcher-os';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'searcher-os-2';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'sentisense-market-intelligence';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'artin0123-gemini-image-mcp-server';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'artin0123-gemini-image-mcp-server-2';
UPDATE servers SET category = '🔒 Security' WHERE id = 'nekzus-npm-sentinel-mcp';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'pratiksha-kanoja-magicslide-mcp-test';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'a-ariff-canvas-instant-mcp';
UPDATE servers SET category = '🔬 Research' WHERE id = 'adamamer20-paper-search-mcp-openai';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'aicastle-school-openai-api-agent-project';
UPDATE servers SET category = '🎓 Education' WHERE id = 'arjunkmrm-tutorials';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'aryankeluskar-poke-video-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'cc25a-openai-api-agent-project123123123';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'ctaylor86-mcp-video-download-server';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'keithah-hostex-mcp';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'kesslerio-attio-mcp-server';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'kodey-ai-salesforce-mcp';
UPDATE servers SET category = '🔬 Research' WHERE id = 'lineex-pubmed-mcp-smithery';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'lukaskostka99-marketing-miner-mcp';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'minionszyw-bazi';
UPDATE servers SET category = '🔬 Research' WHERE id = 'morosss-sdfsdf';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'rfdez-pvpc-mcp-server';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'saidsef-mcp-github-pr-issue-analyser';
UPDATE servers SET category = '🔬 Research' WHERE id = 'shoumikdc-arxiv-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'xinkuang-china-stock-mcp';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'switch';
UPDATE servers SET category = '🧬 Biology & Bioinformatics' WHERE id = 'library-6';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'tensorfeed';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'tensorfeed-2';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'grader';
UPDATE servers SET category = '🔒 Security' WHERE id = 'control-plane';
UPDATE servers SET category = '🎓 Education' WHERE id = 'time-machine';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'timothe-s-growth-calendar';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'trackradar';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'app-store-trends-api';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'app-store-trends-mcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'competitor-tracking-trends-mcp';
UPDATE servers SET category = '🔬 Research' WHERE id = 'upriver';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcp-native-url-security-scanner-that-protects-ai-agent-workflows';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'notch';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'cms';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'variel-mcp-server';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'videozero';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'mcp-37';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'windsor-ai-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'wiplash';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'asmhunter';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'cardog';
UPDATE servers SET category = '🔬 Research' WHERE id = 'citeme';
UPDATE servers SET category = '🔒 Security' WHERE id = 'cleanor';
UPDATE servers SET category = '🔒 Security' WHERE id = 'clearpolicy';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'lotus-ai-citation-intelligence';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'lotus-ai-citation-intelligence-2';
UPDATE servers SET category = '🔒 Security' WHERE id = 'cnvs-app';
UPDATE servers SET category = '🔒 Security' WHERE id = 'cnvs-app-2';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'crawlie';
UPDATE servers SET category = '🔒 Security' WHERE id = 'deviceshelf-server';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'edgelock-trading-journal';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'everjust';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'fluentive-mcp';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'fotohub-creative-ai';
UPDATE servers SET category = '🔒 Security' WHERE id = 'frankki';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'glif';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'havn';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'hinducalendar-panchang-festivals-muhurta';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'joinways';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'miromiro';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'morphed';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'octotrip-flights';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'otto-data-robinhood-chain';
UPDATE servers SET category = '🔬 Research' WHERE id = 'papertext';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'pulltrader-seller-economics';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'pulltrader-seller-economics-2';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'reassign';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'safeship';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'seatcanvas';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'sparks-scribe';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'mcp-40';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'server-3';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'ytbulktranscript';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'energetica-argentine-oil-gas-data';
UPDATE servers SET category = '🔒 Security' WHERE id = 'appgenie-compliance-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'vivid-ads-commerce';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'fipex-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'manda';
UPDATE servers SET category = '🔬 Research' WHERE id = 'forms';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'trade-basis-automotive-appraisal-mcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'wiremi-marketing-mcp';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'captcha-cc-human-verification';
UPDATE servers SET category = '🔒 Security' WHERE id = 'arvi-wine-catalog';
UPDATE servers SET category = '🔒 Security' WHERE id = 'agentdomain-mcp';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'salesforce-devops';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'permits';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'mcp-49';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'creative-claw';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'gitresume';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'heista';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'jacktrade-crm';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'junely-colorado-kids-camps-after-school';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'nexalink-digital-business-card-personal-crm';
UPDATE servers SET category = '🔒 Security' WHERE id = 'tempguru-event-staffing';
UPDATE servers SET category = '🔒 Security' WHERE id = 'tempguru-event-staffing-2';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'valid';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'mentoring-inquiry-builder';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = '1inch-mcp';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'a11y-check';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'a2a2p-agent-to-agent-to-physical';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'mcp-server-17';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'actuallycare';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'agentery';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'agentsprice';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'aikstockdata-korean-stock-data';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'mcp-58';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'airroi';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'anthid';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'appdex';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcp-61';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'arc-security';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'astranl-2';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'astranl-3';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'audiala';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'audioscrape-audio-intelligence';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'aca-automated-client-acquisition-2';
UPDATE servers SET category = '🏢 Workplace & Productivity' WHERE id = 'baby-age';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'earlywire';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'agent-check';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'bellwether-mcp';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'api';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'marketplace';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'bidsparq';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'bidsparq-2';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'mcp-64';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'bisibility';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'blitzreels-video-editor';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'blue-pillow-hotels-stays';
UPDATE servers SET category = '🛒 E-Commerce' WHERE id = 'store';
UPDATE servers SET category = '🔒 Security' WHERE id = 'compliance-batch-alignment';
UPDATE servers SET category = '🔒 Security' WHERE id = 'ofac-sdn-screening';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'sstv-decoder';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'boostermage-mtg-prices';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'boothcheck';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'bozfix';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'breckenwander-travel';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'breckenwander-travel-2';
UPDATE servers SET category = '🔒 Security' WHERE id = 'bright-security';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'calmseo';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'chad-analytics';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'contractor-quote-check';
UPDATE servers SET category = '🎓 Education' WHERE id = 'mind-of-mylo-quotes';
UPDATE servers SET category = '🔒 Security' WHERE id = 'cinderfi-retirement-planning';
UPDATE servers SET category = '🔒 Security' WHERE id = 'cinderfi-retirement-planning-2';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'citehawk';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'cituna-mcp';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'agentmonitorrelay-mcp';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'copilotconnectorledger-mcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'clearpost-wordpress-seo-agent';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'conqueror';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'conqueror-2';
UPDATE servers SET category = '🔒 Security' WHERE id = 'continueops-public-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'costbench';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'costbench-2';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'cost-seg-smart';
UPDATE servers SET category = '🎓 Education' WHERE id = 'courseprofiler';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'coworkingview';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'cpzai';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'mcp-78';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcp-shield';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'mcp-79';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'prism-crossdeck';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'cryptoquant';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'eventtrader-mcp';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'cymosoft';
UPDATE servers SET category = '🔬 Research' WHERE id = 'cytado';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'datadoe-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'daxoom';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'desaira';
UPDATE servers SET category = '🔒 Security' WHERE id = 'dmarkoff-dmarc-spf-dkim-analytics';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'docfork-mcp-2';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'dex-data';
UPDATE servers SET category = '🔒 Security' WHERE id = 'compliance-evidence';
UPDATE servers SET category = '🔒 Security' WHERE id = 'compliance-radar';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'coverage-trigger';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'parcel-edge';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'payer-api-directory';
UPDATE servers SET category = '🧬 Biology & Bioinformatics' WHERE id = 'research-intel';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'title-check';
UPDATE servers SET category = '🧬 Biology & Bioinformatics' WHERE id = 'trial-overdue';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'dukon-ai-billz-store-analytics';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcp-compliance-preflight';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'mcp-server-23';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'familiar';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'second-server';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'filtrous-mcp-catalog-server';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'finerx';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'finn-auto-car-subscription';
UPDATE servers SET category = '🔒 Security' WHERE id = 'framekeep-public-discovery';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'the-front-desk-review';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'gachi-data-api-japan-station-accessibility-data';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'gachi-data-api-japan-station-accessibility-data-2';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'game-industry-library';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcp-agentcore';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'beachfinder-beaches-and-live-conditions';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'human-design';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'munin';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'getmyhotels';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'panes';
UPDATE servers SET category = '🎓 Education' WHERE id = 'sapiens';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'transformseo';
UPDATE servers SET category = '🔒 Security' WHERE id = 'valet-parking-directory';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'wp-agent-wordpress-publishing-management-with-claude';
UPDATE servers SET category = '🔒 Security' WHERE id = 'cosmik';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'predict-prediction-market-data-for-ai-agents';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'halal-terminal';
UPDATE servers SET category = '🔒 Security' WHERE id = 'hatchable';
UPDATE servers SET category = '🔬 Research' WHERE id = 'clarity-by-health-ai';
UPDATE servers SET category = '🔬 Research' WHERE id = 'clarity-by-health-ai-2';
UPDATE servers SET category = '🔬 Research' WHERE id = 'clarity-by-health-ai-3';
UPDATE servers SET category = '🔒 Security' WHERE id = 'health-ai-rigor-precedent-483-risk-radar';
UPDATE servers SET category = '🔒 Security' WHERE id = 'health-ai-rigor-precedent-483-risk-radar-2';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'aisha';
UPDATE servers SET category = '🔒 Security' WHERE id = 'agents';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'holdingsintel';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'horizon-brand-authority-mcp';
UPDATE servers SET category = '🔬 Research' WHERE id = 'how-to-read-the-future';
UPDATE servers SET category = '🔗 Aggregators' WHERE id = 'htag-docs';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'interactive-brokers-ibkr';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'idealo-mcp-server';
UPDATE servers SET category = '🔒 Security' WHERE id = 'imperio-italian-tax-compliance-tools';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'intentwake-audience-intelligence';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'izhost';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'jagannatha-hora-vedic-astrology';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'jeikin';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'jeremy-twogood-portfolio';
UPDATE servers SET category = '🏠 Home Automation' WHERE id = 'mcp-103';
UPDATE servers SET category = '🔒 Security' WHERE id = 'deals';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'kubova-3d-container-loading';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'leadhound-api';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'leadmarina';
UPDATE servers SET category = '🔒 Security' WHERE id = 'leadsapp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'lie-detector-test';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'booking-2';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'llm-abacus';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'logokit-brand-company-data';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'lowvyn';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'lowvyn-2';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'mcp-clay-to-instantly-smartlead-push';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'mcp-gtm-tech-stack-signal-scraper';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'mcp-111';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'api-5';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'markmesh';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'remote-browser-mcp-server-from-mcpbundles';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'the-mcp-census';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'mcpvillage';
UPDATE servers SET category = '🔒 Security' WHERE id = 'md-log-mcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'medrecpro-drug-label-server';
UPDATE servers SET category = '🔒 Security' WHERE id = 'meltema-weather';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'meritvalue';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'seo-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'microsoft-sentinel-data-exploration';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'moltarch';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'moltarch-2';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'momentic';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'workshops';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'mttrly';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'mustertheforce-mcp';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'bible-copilot';
UPDATE servers SET category = '🔒 Security' WHERE id = 'booking-4';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'myhairmail-agent-tools';
UPDATE servers SET category = '🔬 Research' WHERE id = 'conference-partner';
UPDATE servers SET category = '🔬 Research' WHERE id = 'conference-partner-2';
UPDATE servers SET category = '🛒 E-Commerce' WHERE id = 'storefront';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'storefront-2';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'name-brewery-domain-checker';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'ubersuggest';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'coherence-signal';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'a11y-check-2';
UPDATE servers SET category = '🔬 Research' WHERE id = 'nobleblocks-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'nocticas';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'name-check';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'nuditok';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'nullpath-agent-marketplace';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'nusii-mcp-server';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'nvidia-cuda-docs';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'daleel';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'mcp-122';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'obriym-crm';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'octolens';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'copass-remote';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'lasso';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'lasso-2';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'shipping-rates-postage-calculator';
UPDATE servers SET category = '🔒 Security' WHERE id = 'ontoramp-governance-assessment';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'ontoramp-transformation-radar';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'open-house-copilot';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'orshot';
UPDATE servers SET category = '🔒 Security' WHERE id = 'parkinzi';
UPDATE servers SET category = '🔒 Security' WHERE id = 'parkinzi-2';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'persimmon';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'persuadioai';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'pillar-gtm-os';
UPDATE servers SET category = '🖥️ OS Automation' WHERE id = 'pilotgentic';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'pixelixe';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'pixelixe-2';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'pixelixe-3';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'pixserp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'trades';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'trades-2';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'powerstation-platform';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'printing-labs';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'prizmad';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'project-paced';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'promptibus-mcp';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'mcp-server-42';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'qencode';
UPDATE servers SET category = '🔒 Security' WHERE id = 'qualequest-ai-agent-governance-platform';
UPDATE servers SET category = '🔬 Research' WHERE id = 'qubitsok-quantum-computing-jobs-papers-researchers';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'quriov';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'rankworker';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcp-130';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'relm-crm';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'rephonic';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'reply-argus';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'reporting-ninja';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'monitoring-3';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'revorbit-crm';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'vedic-astrology-and-kundli-mcp-server-by-roxyapi';
UPDATE servers SET category = '🔒 Security' WHERE id = 'royal-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'compliance';
UPDATE servers SET category = '🔒 Security' WHERE id = 'zhiji-daily-report-market-brief';
UPDATE servers SET category = '🔒 Security' WHERE id = 'zhiji-signal-market-phase-detection';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'saas-browser';
UPDATE servers SET category = '🔒 Security' WHERE id = 'evidence-ledger';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'sapiens-2';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'sapiens-sint-ticos';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'nem-explorer-scadaminer';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'scout-mcp-local';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'scrap-autos-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcp-133';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'se-ranking';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'serp-agent-seo';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'serpstat';
UPDATE servers SET category = '🔬 Research' WHERE id = 'research';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'sigao-li-personal-mcp-server';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'signed';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'sitelemetry';
UPDATE servers SET category = '🔒 Security' WHERE id = 'skillssafe-security-scanner';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'snaptoll';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'stride-sneaker-shop';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'snitcher';
UPDATE servers SET category = '🔒 Security' WHERE id = 'dependency-management-mcp-server';
UPDATE servers SET category = '🔒 Security' WHERE id = 'dependency-management-mcp-server-2';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'mcp-141';
UPDATE servers SET category = '🏠 Home Automation' WHERE id = 'soracom-knowledge-mcp-server';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'soundgtm';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'splark';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'ssemble-ai-clipping-2';
UPDATE servers SET category = '🔒 Security' WHERE id = 'stackhawk';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'mcp-145';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'hotel-vacation-rental-mcp-live-prices-reviews-across-booking-airbnb-vrbo-google-hotels';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'stockmarketscan';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'stockmarketscan-2';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'stockmarketscan-3';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'stock-trends-market-intelligence';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'streetproof-physical-brand-index';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'optics-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'stock-research-mcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'tastemaker';
UPDATE servers SET category = '🔒 Security' WHERE id = 'the-daily-smark';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'perfex-crm';
UPDATE servers SET category = '🔬 Research' WHERE id = 'academic-research-mcp';
UPDATE servers SET category = '🔬 Research' WHERE id = 'academic-research-mcp-server';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'developer-tools-mcp-server';
UPDATE servers SET category = '🔒 Security' WHERE id = 'domain-intelligence-mcp-server';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'github-mcp-server';
UPDATE servers SET category = '🔬 Research' WHERE id = 'sec-corporate-events-mcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'seo-web-analysis-mcp-server';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'youtube-media-mcp-server';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'tickerall';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'times-rare';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'tls-radar';
UPDATE servers SET category = '🔬 Research' WHERE id = 'tomesphere';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'finoptima';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'transcriptfetch';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'translatesheet';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'yultrace-bounty-feed';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'dango';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'spook-seo';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'tw-market-data';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'ugc-pocket';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'mcp-152';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'pancake-verifiable-backtests-for-ai-agents';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'validoria-mcp';
UPDATE servers SET category = '🔬 Research' WHERE id = 'latin';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'video-assistant-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'flow';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'vendo-ai';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'vendooly';
UPDATE servers SET category = '🧬 Biology & Bioinformatics' WHERE id = 'supplement-advisor-mcp';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'versium-reach';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'vidmoat';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'virohana-business';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'voltcast';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'vouchedpros';
UPDATE servers SET category = '🔒 Security' WHERE id = 'wafergraph-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'walnai-website-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'washlib';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'mu';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'amazon-product-research-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'wick-funded-trading';
UPDATE servers SET category = '🔒 Security' WHERE id = 'wikexa-knowledge';
UPDATE servers SET category = '🔒 Security' WHERE id = 'wildrun-mcp-validator';
UPDATE servers SET category = '🔒 Security' WHERE id = 'wp-healthkit';
UPDATE servers SET category = '🔒 Security' WHERE id = 'wp-healthkit-2';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'wpwriter-for-wordpress';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'xdog-trading';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'matflow';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'zahabprice-live-gold-silver-prices';
UPDATE servers SET category = '🔒 Security' WHERE id = 'website-search';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'analytics';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'zetadeck';
UPDATE servers SET category = '🔬 Research' WHERE id = 'zoningverdict';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'zyberno-brina-gap-stock-analysis';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'agent-tools-2';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'agent-tools-3';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'agent-tools-4';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'audioknihy-cz-catalog';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'ai-visibility';
UPDATE servers SET category = '🔒 Security' WHERE id = 'lebenslaufheld';
UPDATE servers SET category = '🔒 Security' WHERE id = 'nomado24-remote-jobs';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'ai-agent-tokenized-stock-os';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'mcp-server-49';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'agentseo';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'arlet';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'busymate-devtools';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'mcp-167';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'clipkit';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'ddplus';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'ai-brand-watch-by-desvela';
UPDATE servers SET category = '🔒 Security' WHERE id = 'draugr';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'drengr';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'goldprice-dev';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcp-170';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'metamesh-uga-2';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'metamesh-uga-3';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'metarun';
UPDATE servers SET category = '📊 Data Platforms' WHERE id = 'oh-my-posh-validator';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'rampify';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'repofold';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'repowise-hosted';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'sexai-mcp';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'sexai-mcp-2';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'slideforge';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'stackfiesta';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'tidesman';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'vibeseo';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'whatcanido-mcp-server-for-service-businesses';
UPDATE servers SET category = '🎓 Education' WHERE id = 'sefaria-library';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'afbudsrejser-travel-search';
UPDATE servers SET category = '🔒 Security' WHERE id = 'el-pujante-subastas-p-blicas-de-espa-a';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'propertylist-spanish-property-mls';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'cuttingtoolsai-grade-cross-reference';
UPDATE servers SET category = '🔒 Security' WHERE id = 'departi-travel-compliance-curated-booking';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'dockhold';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'sorted-event-registration-queue-management';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'akkilahdot-travel-search';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'zxoar';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'brandyze';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'catalogue';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'hel';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'medrates';
UPDATE servers SET category = '🔒 Security' WHERE id = 'guest';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'grocery';
UPDATE servers SET category = '🛒 E-Commerce' WHERE id = 'storefront-3';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'us-stocks-market-data';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = '3dpack-ing-container-truck-load-planning';
UPDATE servers SET category = '🔬 Research' WHERE id = 'mcp-180';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'afterlaunch-the-agentic-growth-marketing-engine';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'anakin';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'aemo-mcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'brandfetch';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'brandfetch-2';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'agentic-ops';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'agentic-ops-2';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'imperium-manifold';
UPDATE servers SET category = '🛒 E-Commerce' WHERE id = 'defiance-storefront';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'dxb-data';
UPDATE servers SET category = '🔒 Security' WHERE id = 'feedoracle-compliance-agent';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'framelane';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'frase-seo';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'frase-seo-2';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'frase-seo-3';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'futia';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'mcp-188';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'mcp-189';
UPDATE servers SET category = '🔒 Security' WHERE id = 'phishunt';
UPDATE servers SET category = '🔒 Security' WHERE id = 'rubric-protocol';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'mcp-1786400436227';
UPDATE servers SET category = '📊 Monitoring' WHERE id = '1clickreport';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'sense2-promotional-products';
UPDATE servers SET category = '🔒 Security' WHERE id = 'vigo-mcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'stylemcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'ibo';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'video-generation-cost-estimator';
UPDATE servers SET category = '🔒 Security' WHERE id = 'the-metis-fca-handbook-ai-harness-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'mcp-server-kalshi';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'yandex-audience-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'yandex-merchants-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'yango-tech-retail-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'atom-pricing-intelligence';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'stockfacts';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'monitoring-aiops';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'digestseo-mcp-geo-ai-visibility-mcp-server';
UPDATE servers SET category = '🔒 Security' WHERE id = 'myinvois-mcp';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'quash-mobile-app-automation';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'sniff';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'mcp-acedatacloud';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'mcp-grok';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'mcp-hailuo';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'mcp-kling';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'mcp-luma';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'mcp-luma-2';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'mcp-minimax';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'mcp-seedance';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'mcp-seedance-2';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'mcp-sora';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'mcp-sora-2';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'mcp-veo';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'mcp-veo-2';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'mcp-wan';
UPDATE servers SET category = '🔒 Security' WHERE id = 'ybe-check';
UPDATE servers SET category = '🖥️ OS Automation' WHERE id = 'mac-control-mcp';
UPDATE servers SET category = '🔗 Aggregators' WHERE id = 'vantagate-mcp-server';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'copilot-studio-friction-index';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'adsturbo-creative-mcp';
UPDATE servers SET category = '🔬 Research' WHERE id = 'quredec';
UPDATE servers SET category = '🔬 Research' WHERE id = 'africa-data-bank';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'google-play-console-mcp';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'kafka-dataops-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'windows-management';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'india-stock-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'ai-firewall-mcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'serpmantics';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'oss-issues-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'promptspend';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'call-copilot';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'lorem';
UPDATE servers SET category = '🔬 Research' WHERE id = 'uk-break-clause-analyzer';
UPDATE servers SET category = '🔒 Security' WHERE id = 'ot-security-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'uk-crop-nutrients';
UPDATE servers SET category = '🔒 Security' WHERE id = 'uk-environmental-compliance';
UPDATE servers SET category = '🔒 Security' WHERE id = 'us-regulations-mcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'argo-mcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'minipainter';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'askcyborg';
UPDATE servers SET category = '🔬 Research' WHERE id = 'ipcc-ar6-climate-retrieval';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'sharedoc-mcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'ai-seo';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'founder';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'agenthook';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'la-palma-24-vacation-rentals';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'bedc-mcp';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'freight-pulse';
UPDATE servers SET category = '🔬 Research' WHERE id = 'haypile';
UPDATE servers SET category = '🔬 Research' WHERE id = 'bda-mcp';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'accessibility-scanner-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'domainintel-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'riskmodels';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'x402nano';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'brandsystem-mcp-build';
UPDATE servers SET category = '🔒 Security' WHERE id = 'veridion-nexus';
UPDATE servers SET category = '🔬 Research' WHERE id = 'browseai-dev';
UPDATE servers SET category = '🔒 Security' WHERE id = 'a2a-governance-bridge-mcp';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'accessibility-ai-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'ai-incident-reporting-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'ai-ops-mcp';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'aml-ai-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'care-home-cqc-mcp';
UPDATE servers SET category = '🧬 Biology & Bioinformatics' WHERE id = 'clinical-trials-ai-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'code-reviewer-ai-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'construction-iso-19650-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'coppa-ferpa-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'cqc-compliance-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'cra-compliance-mcp';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'crm-ai-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'csrd-compliance-mcp';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'deepfake-detector-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'domiciliary-care-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'flight-logger-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'gdpr-compliance-ai-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'haulage-uk-compliance-mcp';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'health-check-ai-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'korea-ai-basic-act-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'llm-compliance-comparison-mcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'marketing-analytics-ai-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcp-spec-compliance-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'meok-attestation-verify';
UPDATE servers SET category = '🔒 Security' WHERE id = 'meok-enterprise-compliance-checker';
UPDATE servers SET category = '🔒 Security' WHERE id = 'meok-enterprise-compliance-suite';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'meok-eu-platform-worker-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'meok-vehicle-handover-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'mifid-ii-ai-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'nis2-compliance-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'nrswa-ai-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'planthire-ai-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'security-scanner-ai-mcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'seo-checker-ai-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'stock-analyzer-ai-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'uk-ai-act-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'uk-ai-bill-compliance-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'watermarking-authenticity-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'agentfulfyl';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'casthub';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'hubspot-integrations-mcp';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'pingcheck-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'cigarfinder';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcp-scan';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'newsgurus-intel';
UPDATE servers SET category = '🔒 Security' WHERE id = 'company-gi';
UPDATE servers SET category = '🔒 Security' WHERE id = 'company-gibraltar';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'compuute-mcp-security-scanner';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'fragments-mcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'ai-brand-visibility-tracker';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'convergealpha';
UPDATE servers SET category = '🔒 Security' WHERE id = 'crowdstrike-falcon-mcp-server';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'myvideogift';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'design-constraint-validator';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'custom-blinds-shop';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'rollin-mcp-server';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'defenter-proxy';
UPDATE servers SET category = '🔒 Security' WHERE id = 'value-us';
UPDATE servers SET category = '🔒 Security' WHERE id = 'dingdawg-compliance';
UPDATE servers SET category = '🔗 Aggregators' WHERE id = 'openapi';
UPDATE servers SET category = '🎓 Education' WHERE id = 'sports-context-protocol';
UPDATE servers SET category = '🔬 Research' WHERE id = 'source-library';
UPDATE servers SET category = '🔒 Security' WHERE id = 'pagerunner';
UPDATE servers SET category = '🔒 Security' WHERE id = 'ibmz';
UPDATE servers SET category = '🔒 Security' WHERE id = 'exposureguard';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'swisstrip-mcp';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'ghcli-mcp-connector';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'github-mcp-connector';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'dyslex-ia';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'quant-research-mcp';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'scout';
UPDATE servers SET category = '🔬 Research' WHERE id = 'methods-mcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'brand-intelligence-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'regulatory-compliance-intelligence-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'stock-market-data-mcp';
UPDATE servers SET category = '🔬 Research' WHERE id = 'patent-intelligence-mcp';
UPDATE servers SET category = '🔬 Research' WHERE id = 'citeguard';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'gecko-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'furlpay-cli';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'compliance-intelligence';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'freeastroapi-astrology';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'project-brain';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'analook-competitor-intelligence';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'analook-competitor-intelligence-2';
UPDATE servers SET category = '🔒 Security' WHERE id = 'agentgauge';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'oak-longevity-mcp-server';
UPDATE servers SET category = '🔒 Security' WHERE id = 'painprep-mcp-server';
UPDATE servers SET category = '🔒 Security' WHERE id = 'gorgon-scout';
UPDATE servers SET category = '📊 Data Platforms' WHERE id = 'great-question';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'claude-real-video';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'openai-ads-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'stock-image-mcp';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'crystallize-mcp';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'slidemaster';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'slidemaster-2';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'mansa-african-markets';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'hit-the-road-rentals';
UPDATE servers SET category = '🧬 Biology & Bioinformatics' WHERE id = 'hormonaly-clinical-intelligence';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'pops4-mcp-catalog';
UPDATE servers SET category = '🔬 Research' WHERE id = 'onecite';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'packzoo';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'powershell-mcp';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'atlas-pipeline';
UPDATE servers SET category = '🔒 Security' WHERE id = 'backgen';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'sfmc-mcp-server';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'apollo-io-mcp-server';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'ironclaw';
UPDATE servers SET category = '🔒 Security' WHERE id = 'storebridge-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'agent-venue-radar';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'opencut-controller';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'maasy-ai-marketing-copilot';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'market-data-toolkit-mcp';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'macos-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'brightspace';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'jmpy-mcp-server';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'canvas-api-mcp';
UPDATE servers SET category = '🖥️ OS Automation' WHERE id = 'apple-calendar';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'scrcpy-mcp';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'audio-analyzer';
UPDATE servers SET category = '🔒 Security' WHERE id = 'meridian-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'agnigateway-marketplace';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'vidnotes';
UPDATE servers SET category = '🔒 Security' WHERE id = 'fedramp-20x-requirements';
UPDATE servers SET category = '🔒 Security' WHERE id = 'gdpr-shift-left-compliance';
UPDATE servers SET category = '🔒 Security' WHERE id = 'judges-panel';
UPDATE servers SET category = '🔬 Research' WHERE id = 'agentcite';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'ui-design-to-code';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'kochava-for-advertisers';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'openvan-travel';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'korext-ai-code-governance';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcp-seatbelt';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'kloakt';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'agentic-prompt';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'testmu-ai-formerly-lambdatest';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'testmu-ai-formerly-lambdatest-2';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'priceparse';
UPDATE servers SET category = '🔒 Security' WHERE id = 'warden';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'mcp-199';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'sistrix-seo-toolbox';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'fossick';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'localpro-verified-us-local-service-provider-data';
UPDATE servers SET category = '🔗 Aggregators' WHERE id = 'lockspec';
UPDATE servers SET category = '🔒 Security' WHERE id = 'overdrive-intel';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'fatestar-ziwei';
UPDATE servers SET category = '🖥️ OS Automation' WHERE id = 'lucid-apple-mcp';
UPDATE servers SET category = '🔬 Research' WHERE id = 'paper-search-arxiv-semantic-scholar-openalex';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcpshield';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'mcpower-security-proxy';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'scribefy';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'atag-mcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'content-genie';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'test-genie';
UPDATE servers SET category = '🎓 Education' WHERE id = 'ntnu-courses-unofficial';
UPDATE servers SET category = '🎓 Education' WHERE id = 'learnthat-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'nyc-property-venue-api';
UPDATE servers SET category = '🔒 Security' WHERE id = 'safeinstall';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'bountyverdict-agent-decision-tools';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'mobai-mcp';
UPDATE servers SET category = '🖥️ OS Automation' WHERE id = 'toolpiper';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'modellix-agent-canvas';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'stockmatrix-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'open-registry-poc';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'update-hijack-demo';
UPDATE servers SET category = '🔒 Security' WHERE id = 'update-hijack-poc';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'hoshy';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'dispatchseo';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'stratevo';
UPDATE servers SET category = '🧬 Biology & Bioinformatics' WHERE id = 'health-api';
UPDATE servers SET category = '🧬 Biology & Bioinformatics' WHERE id = 'health-api-2';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'tradeti-me-market-hours';
UPDATE servers SET category = '🔒 Security' WHERE id = 'vectordecisions-mcp-server';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'gread';
UPDATE servers SET category = '🔒 Security' WHERE id = 'insaits-ai-communication-security-monitor';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'eu-safety-gate-product-recalls';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'canton-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'suprsonic-mcp';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'cce-mcp-server';
UPDATE servers SET category = '🔒 Security' WHERE id = 'data-compliance-classifier-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'vat-validator-mcp';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'inkmotion';
UPDATE servers SET category = '🔒 Security' WHERE id = 'onplana';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'zaai-dev-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'packrift-mcp';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'alphalabs-intelligence';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'admob-mcp-server';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'vertaaux-mcp';
UPDATE servers SET category = '🧬 Biology & Bioinformatics' WHERE id = 'phi-longevity-prism';
UPDATE servers SET category = '🧬 Biology & Bioinformatics' WHERE id = 'phi-longevity-prism-2';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'stock-moves-explained';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'stock-moves-explained-2';
UPDATE servers SET category = '📊 Data Platforms' WHERE id = 'posthog-mcp-server';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'sf-intelligence';
UPDATE servers SET category = '🔒 Security' WHERE id = 'prismix-status-mcp';
UPDATE servers SET category = '🖥️ OS Automation' WHERE id = 'hunch';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'mcp-pronto';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'provar-mcp-server';
UPDATE servers SET category = '🖥️ OS Automation' WHERE id = 'macos-calendar-and-reminders';
UPDATE servers SET category = '🔒 Security' WHERE id = 'vaspera-hardening';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'bitrix24-mcp';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'mcp-1c';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'local-leads-mcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'seo-stack-mcp';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'reposcout';
UPDATE servers SET category = '🔒 Security' WHERE id = 'spineframe';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'ocular-audio-mcp';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'awesome-copilot-mcp-server';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'hindsight-mcp';
UPDATE servers SET category = '🏠 Home Automation' WHERE id = 'regennexus-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'gmo-coin-fx-mcp-server';
UPDATE servers SET category = '🔒 Security' WHERE id = 'security-orchestra';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'ai-price-index';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'llmscout';
UPDATE servers SET category = '🔒 Security' WHERE id = 'agentpay-sentinel-mcp';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'mcp-203';
UPDATE servers SET category = '🔬 Research' WHERE id = 'orcid';
UPDATE servers SET category = '🔬 Research' WHERE id = 'scopus';
UPDATE servers SET category = '🔬 Research' WHERE id = 'semanticscholar';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'dora-mcp';
UPDATE servers SET category = '🔬 Research' WHERE id = 'search-papers';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'agentic-sdlc-mcp';
UPDATE servers SET category = '🔬 Research' WHERE id = 'advertising-protocols';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'mcp-204';
UPDATE servers SET category = '🔬 Research' WHERE id = 'science-ai-journal-mcp-server';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'llm-brand-monitor';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'stock-sentinel';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'silicon-analysts';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'fleet-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'thinchain';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'agentburn';
UPDATE servers SET category = '🔗 Aggregators' WHERE id = 'voc-openapi-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'sonarqube-mcp-server';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'korean-agriculture-market-data';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'top-gun-geo-lens';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'domain-finder';
UPDATE servers SET category = '🔒 Security' WHERE id = 'conformy';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'video-reader-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcp-208';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'mcp-209';
UPDATE servers SET category = '🔬 Research' WHERE id = 'crossref-mcp-server';
UPDATE servers SET category = '🔬 Research' WHERE id = 'pubmed-mcp-server';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'indiamart-mcp-server';
UPDATE servers SET category = '🔒 Security' WHERE id = 'universal-connector-mcp';
UPDATE servers SET category = '🔗 Aggregators' WHERE id = 'eyeot-erp';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'librarian';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'gold-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'okaneland-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'vetted-consumer';
UPDATE servers SET category = '🔬 Research' WHERE id = 'academic-research-mcp-server-2';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'google-maps-mcp-server-2';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'chutes-media-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'thinkreview';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'thrivestack-plg-crm';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'charlotte';
UPDATE servers SET category = '🔒 Security' WHERE id = 'asymptotic-ethics';
UPDATE servers SET category = '🔒 Security' WHERE id = 'federated-ai-commons';
UPDATE servers SET category = '🔒 Security' WHERE id = 'elasticsearch';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'execufunction';
UPDATE servers SET category = '🔬 Research' WHERE id = 'topolift-negotiation';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'sphior-code-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'mcp-server-78';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'mediaengine';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'figma-ui-mcp';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'blobpedia';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'vugola-mcp';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'androjack-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'release-gate';
UPDATE servers SET category = '🔒 Security' WHERE id = 'aiegis';
UPDATE servers SET category = '🔒 Security' WHERE id = 'attestix';
UPDATE servers SET category = '🎓 Education' WHERE id = 'vonage-documentation-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'waysway';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'lgl-mcp-server';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'video-loom';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'xrpname-mcp-server';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'bilibili-mcp-server';
UPDATE servers SET category = '🎓 Education' WHERE id = 'supermemory';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'devilge';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'mcp-server-82';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'creator-seo-mcp';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'marketo';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'launch-engine';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'salesforce-cloud';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'servicenow-mcp-server-nowaikit';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'hotin';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'abm-mcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'abm-mcp-2';
UPDATE servers SET category = '📊 Data Platforms' WHERE id = 'willitsend';
UPDATE servers SET category = '🔒 Security' WHERE id = 'pkgxray';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'fastmcp-server-for-apollo';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'self-hosted-github-mcp-server';
UPDATE servers SET category = '🖥️ OS Automation' WHERE id = 'macos-only-mcp-server-that-exposes-imessage-chat';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'adopte-un-conteneur-container-delivery-pricing';
UPDATE servers SET category = '🖥️ OS Automation' WHERE id = 'calendarmcp-2';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'chartpane';
UPDATE servers SET category = '🔒 Security' WHERE id = 'ai-supply';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'acf-mcp';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'acf-mcp-2';
UPDATE servers SET category = '🔒 Security' WHERE id = 'prism-scanner';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'github';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'apiany-mcp';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'rigol-dho824-oscilloscope-2';
UPDATE servers SET category = '🔬 Research' WHERE id = 'litra-paper-search';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'android-security-analyzer';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'appstoreconnect-mcp';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'arduino-mcp-server';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'kylas-crm';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'artefact-revenue-intelligence';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'makers-page-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'hares-mcp-security-scanner';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'tripwire';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'video-overlay-kit';
UPDATE servers SET category = '🔒 Security' WHERE id = 'npm-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'indian-nse-stock-insights';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'seopro-ai';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'seopro-ai-2';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'alphasmo-tools';
UPDATE servers SET category = '🔒 Security' WHERE id = 'altr-mcp-server';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'furlen-mcp-2';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'amzscout-skill-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'anaconda-mcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'missinglinkz';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'vinted-mcp';
UPDATE servers SET category = '🎓 Education' WHERE id = 'ololand-dd';
UPDATE servers SET category = '🖥️ OS Automation' WHERE id = 'imessage-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'ground-truth';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'blatui';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'ng-blatui';
UPDATE servers SET category = '🖥️ OS Automation' WHERE id = 'mac-use-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'apiiro-guardian-agent';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'apollo-io';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mosta-net';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'star-trajectory';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'index-now-ru';
UPDATE servers SET category = '🔒 Security' WHERE id = 'dvalincode';
UPDATE servers SET category = '🔬 Research' WHERE id = 'arxivsub-mcp';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'ascript-mcp';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'opchain';
UPDATE servers SET category = '🔒 Security' WHERE id = 'grasp-codebase-analysis-architecture-intelligence';
UPDATE servers SET category = '👤 Customer Data Platforms' WHERE id = 'zoho-crm';
UPDATE servers SET category = '🔬 Research' WHERE id = 'statcite';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'webear';
UPDATE servers SET category = '🎓 Education' WHERE id = 'gossipcat';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'atheris-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'varrd';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'enhance-mcp';
UPDATE servers SET category = '🎥 Multimedia Process' WHERE id = 'media-mcp';
UPDATE servers SET category = '🎯 Marketing' WHERE id = 'pushengage';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcp-server-for-oscal';