UPDATE servers SET category = '📋 Product Management' WHERE id = '3knightcz-codebeamer-mcp';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'a-25-ios-mcp-code-quality-server';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'abrinsmead-mindpilot-mcp';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'admica-filescopemcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'akramiot-mcp-ai-soc-sher';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'aktsmm-skill-ninja-mcp-server';
UPDATE servers SET category = '💬 Communication' WHERE id = 'alimo7amed93-webhook-tester-mcp';
UPDATE servers SET category = '💬 Communication' WHERE id = 'ambar-simctl-mcp';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'api7-apisix-mcp';
UPDATE servers SET category = '🔗 Aggregators' WHERE id = 'automation-ai-labs-mcp-link';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'avisangle-jenkins-mcp-server';
UPDATE servers SET category = '🎓 Education' WHERE id = 'ayhammouda-python-docs-mcp-server';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'back1ply-agent-skill-loader';
UPDATE servers SET category = '🔗 Aggregators' WHERE id = 'bbonnin-openapi-to-mcp';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'bgauryy-octocode-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'bishop81-imagedimensions-mcp';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'bitrise-io-bitrise-mcp';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'buildkite-buildkite-mcp-server';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'gavelcode-gavel';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'get-tmonier-argot';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'higress-group-higress-ops-mcp-server';
UPDATE servers SET category = '🔒 Security' WHERE id = 'hoklims-stacksfinder-mcp';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'inditextech-mcp-server-simulator-ios-idb';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'io-github-hoainho-podium-mcp';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'ios-simulator-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'janreges-ai-distiller-mcp';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'joshuarileydev-simulator-mcp-server';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'jungle-grid-mcp-server';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'kevinswint-xcode-studio-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'kyanitelabs-checkyourself';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'muhannad-hash-git-context-mcp';
UPDATE servers SET category = '💬 Communication' WHERE id = 'ozers-hooksense-mcp';
UPDATE servers SET category = '💬 Communication' WHERE id = 'pipepie-pipepie';
UPDATE servers SET category = '🔒 Security' WHERE id = 'rm-rf-prod-groundtruth-mcp';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'sdglbl-mcp-claude-code';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'srijanshukla18-xray';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'theserverlessdev-wsc';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'tosin2013-mcp-adr-analysis-server';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'veelenga-claude-mermaid';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'yuchenssr-mindmap-mcp-server';
UPDATE servers SET category = '🔒 Security' WHERE id = 'kushaim-practice-fusion-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'thehealthai-fda-risk-radar-mcp';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'manzanas';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'auteng-mcp-markdown-publishing-document-share-links';
UPDATE servers SET category = '🔒 Security' WHERE id = 'audit';
UPDATE servers SET category = '💬 Communication' WHERE id = 'apprise-rmcp';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'labby';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'labby-2';
UPDATE servers SET category = '🔒 Security' WHERE id = 'djzs-trust-mcp';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'gateway';
UPDATE servers SET category = '🔒 Security' WHERE id = 'etincel-nonfiction';
UPDATE servers SET category = '🔒 Security' WHERE id = 'helixar-security';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'jeda-ai';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'jeda-ai-2';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'just-domain';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcp-server-2';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcpmyadmin';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'modelrunner';
UPDATE servers SET category = '🔒 Security' WHERE id = 'ninar-ai';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'banking-intelligence';
UPDATE servers SET category = '🔒 Security' WHERE id = 'openaso';
UPDATE servers SET category = '🔒 Security' WHERE id = 'scout-by-optimly';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'orggen-ai';
UPDATE servers SET category = '🔒 Security' WHERE id = 'publishwith-ai';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = '370-ai-ai-gateway-video-seedance-2-0-wan-happyhorse-image-speech-100-chat-models';
UPDATE servers SET category = '🔒 Security' WHERE id = 'scamverify-threat-verification';
UPDATE servers SET category = '🔒 Security' WHERE id = 'seocrawl-ai';
UPDATE servers SET category = '🔒 Security' WHERE id = 'pablolec-keyprobe-mcp';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'gate';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'sugra-api';
UPDATE servers SET category = '🔒 Security' WHERE id = 'spotlight';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'timix-ai';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'vantic';
UPDATE servers SET category = '🔒 Security' WHERE id = 'audit-2';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'structforge';
UPDATE servers SET category = '🔒 Security' WHERE id = 'taste';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'lucid';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'argentina-invoices-factura-electr-nica-cae-via-wsfe';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'belgium-invoices-peppol-bis-3-0-via-storecove';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'brazil-invoices-nfs-e-nota-fiscal-de-servi-o';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'chile-invoices-dte-boleta-factura-electr-nica-via-openfactura';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'colombia-invoices-dian-factura-electronica-via-matias-api';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'costa-rica-invoices-hacienda-comprobante-electronico-v4-4';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'denmark-invoices-peppol-nemhandel-via-storecove';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'dominican-republic-invoices-dgii-e-cf-facturacion-electronica';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'ecuador-invoices-factura-electr-nica-sri-via-datil';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'finland-invoices-peppol-bis-3-0-via-storecove';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'greece-invoices-aade-mydata-national-api';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'hungary-invoices-nav-online-szamla-3-0-reporting-api';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'india-invoices-gst-e-invoicing-irn-via-irp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'india-payments-razorpay-payment-links-upi-cards-netbanking';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'italy-invoices-fatturapa-sdi-via-invoicetronic';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'korea-invoices-popbill-issue-query-nts-transmit';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'luxembourg-invoices-peppol-bis-3-0-via-storecove';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'malaysia-invoices-lhdn-myinvois-submit-query-cancel';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'mexico-invoices-cfdi-4-0-factura-electr-nica';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'netherlands-invoices-peppol-bis-3-0-via-storecove';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'nigeria-invoices-firs-nrs-mbs-e-invoicing-irn';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'norway-invoices-peppol-bis-3-0-ehf-via-storecove';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'paraguay-invoices-sifen-e-kuatia-via-facturasend';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'peru-invoices-cpe-factura-boleta-electr-nica-via-nubefact';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'poland-invoices-ksef-2-0-national-e-invoice-api';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'romania-invoices-anaf-e-factura-national-api';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'saudi-invoices-zatca-fatoora-phase-2-reporting-clearance';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'serbia-invoices-sef-efaktura-national-api';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'sweden-invoices-peppol-bis-3-0-via-storecove';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'taiwan-payments-e-invoice-ecpay';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'thailand-e-tax-invoices-leceipt-create-poll-download';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'uruguay-invoices-dgi-e-factura-cfe-merchant-signed-soap-relay';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'vietnam-invoices-misa-meinvoice-create-publish-query';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = '9192-public-compute';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'canada-payroll-employer-cost-take-home-math-2026';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'flatcash-mcp';
UPDATE servers SET category = '💬 Communication' WHERE id = 'the-colony';
UPDATE servers SET category = '🔒 Security' WHERE id = 'pentatrail-ctem';
UPDATE servers SET category = '🔒 Security' WHERE id = 'promptguard';
UPDATE servers SET category = '💬 Communication' WHERE id = 'webhook-co';
UPDATE servers SET category = '💬 Communication' WHERE id = 'whooshly-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'acp-mcp-server';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'allpdfmagic';
UPDATE servers SET category = '💬 Communication' WHERE id = 'almured';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'atlasemoji';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'axiorank-agent-firewall';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'axiorank-zero-trust-for-ai-agents';
UPDATE servers SET category = '🔒 Security' WHERE id = 'aribot-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'bravos-ai';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'chartforge';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'nexus';
UPDATE servers SET category = '🔒 Security' WHERE id = 'a2adependencyinspector-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'a2aidentitytoll-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'a2areplayreceipt-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'agentichtmlexportqa-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'agentskillupdategate-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'aistudioandroidreleasegate-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'aistudioworkspaceapproval-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'aiwaiverdesk-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'androidcliagentgate-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'antigravityextensiongate-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'antigravityrunledger-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'c2padisclosure-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'c2paintake-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'clawmanagerfleet-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'clianythingharness-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'codegworkspace-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'context7docs-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'copilotcliswitchgate-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'decapodkernel-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'equiblesagent-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'fastmcpruntime-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'geminiomnirights-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'hyperframesrender-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcpdeprecation-mcp';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'mcpgatewaydesk-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcpscopeconsent-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'opendesignguard-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'pptmasterdeck-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'schemadriftgate-mcp';
UPDATE servers SET category = '🔎 Search & Data Extraction' WHERE id = 'semblecodesearchgate-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'shipswiftcomponents-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'skybridgepackager-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'speckitacceptance-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'sregymgate-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'statewrightgate-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'universalcartmerchantgate-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'veocreditwaste-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'webmcpactionreceipt-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'zeroidagent-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'zerolangcompiler-mcp';
UPDATE servers SET category = '📋 Product Management' WHERE id = 'consentlayer';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'coordinalo-service-business-operations';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'coordinalo-service-business-operations-2';
UPDATE servers SET category = '🔒 Security' WHERE id = 'crimson-crawler';
UPDATE servers SET category = '🔒 Security' WHERE id = 'seo-audit-2';
UPDATE servers SET category = '🔒 Security' WHERE id = 'deploy-to-agents';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'dintak-mcp-gateway';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'ecoexperten-energieausweis';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'ai-agent-firewall';
UPDATE servers SET category = '🔒 Security' WHERE id = 'gentkey';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'holdings-invoicing';
UPDATE servers SET category = '🔒 Security' WHERE id = 'directory-2';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'hojincheck-japanese-corporate-verification-api-hojin-corporate-entity';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'ifthenpay-payments-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'incisory';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'tebra';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'jithox-e-invoice';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'jithox-e-invoice-readiness';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'jupiter-invoice';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'jupitersignup';
UPDATE servers SET category = '🔒 Security' WHERE id = 'knotrik-appsheet-intelligence';
UPDATE servers SET category = '🔒 Security' WHERE id = 'knowa';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'loop-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'mandateshield-ai-payment-authority';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'mandateshield-ai-payment-authority-2';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'mcpmux';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'mermaid-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'neutral-skincare-reference';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'mcp-server-36';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'agts-mcp-server';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'octura-solutions-site-tools';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'partglyph-mcp-gateway';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'api-6';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'qualy';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'zhiji-llm-router-signal-gateway';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'protect-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcp-132';
UPDATE servers SET category = '🔒 Security' WHERE id = 'intent-engineering';
UPDATE servers SET category = '🔒 Security' WHERE id = 'seogrep';
UPDATE servers SET category = '📋 Product Management' WHERE id = 'ship24-tracking';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'usedbikecenter-zama';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'siglume-mcp-gateway';
UPDATE servers SET category = '🔒 Security' WHERE id = 'squirrelscan';
UPDATE servers SET category = '🔒 Security' WHERE id = 'squirrelscan-2';
UPDATE servers SET category = '🔒 Security' WHERE id = 'audit-3';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'enterprise-mcp-gateway';
UPDATE servers SET category = '🔒 Security' WHERE id = 'intelthreadlinqs-mcp';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'intelligence-gateway';
UPDATE servers SET category = '🔒 Security' WHERE id = 'truss-threat-intelligence';
UPDATE servers SET category = '🔒 Security' WHERE id = 'trustnotch';
UPDATE servers SET category = '🔒 Security' WHERE id = 'yultrace-audit';
UPDATE servers SET category = '🔒 Security' WHERE id = 'yultrace-audit-2';
UPDATE servers SET category = '🔒 Security' WHERE id = 'aegis';
UPDATE servers SET category = '🔒 Security' WHERE id = 'allowance-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'allowance-mcp-2';
UPDATE servers SET category = '💬 Communication' WHERE id = 'webhook-studio';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'xcodebuildmcp';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'xcodebuildmcp-2';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'zyla-api-hub';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'fakturai-german-e-invoice-zugferd-factur-x-e-rechnung';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'constitution-lint';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'appcontext';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'archgraph';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'metamesh-uga';
UPDATE servers SET category = '🔒 Security' WHERE id = 'openaeo';
UPDATE servers SET category = '🔒 Security' WHERE id = 'satrank-lightning-trust-audit-oracle';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'slipstack-pdf';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'mexican-payroll-tax-calculator';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'check-digits';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'torify-japanese-locale-apis-for-ai-agents';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'torify-japan-locale-apis-for-ai-agents';
UPDATE servers SET category = '💬 Communication' WHERE id = 'catchr';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'contix';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'averta-mcp-gateway';
UPDATE servers SET category = '📋 Product Management' WHERE id = 'consentstack';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'mcp-185';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'domaindrift';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'draw-io';
UPDATE servers SET category = '💬 Communication' WHERE id = 'mcp-186';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'formio-uag';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'routara-llm-gateway';
UPDATE servers SET category = '🔒 Security' WHERE id = 'compliance-aiops';
UPDATE servers SET category = '🔒 Security' WHERE id = 'endpoint-aiops';
UPDATE servers SET category = '🔒 Security' WHERE id = 'fabric-aiops';
UPDATE servers SET category = '🔒 Security' WHERE id = 'minio-aiops';
UPDATE servers SET category = '🔒 Security' WHERE id = 'network-aiops';
UPDATE servers SET category = '🔒 Security' WHERE id = 'proxmox-aiops';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'proxy-aiops';
UPDATE servers SET category = '🔒 Security' WHERE id = 'truenas-aiops';
UPDATE servers SET category = '🔒 Security' WHERE id = 'veeam-aiops';
UPDATE servers SET category = '🔒 Security' WHERE id = 'xcp-ng-aiops';
UPDATE servers SET category = '🔒 Security' WHERE id = 'web-validator-by-digestseo';
UPDATE servers SET category = '🔒 Security' WHERE id = 'xaps-mcp-server';
UPDATE servers SET category = '🔒 Security' WHERE id = 'ui-ux-suite';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'agent-payment-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'specularis-ai-visibility-audit';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'muapi';
UPDATE servers SET category = '🔒 Security' WHERE id = 'archiet-audit';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'uk-farm-subsidies';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'visibly-ai-seo-mcp-server';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'agent-payment-mcp-2';
UPDATE servers SET category = '🔒 Security' WHERE id = 'fake-star-audit';
UPDATE servers SET category = '🔒 Security' WHERE id = 'ci-sentinel';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'cejel';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'open-brain';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'trust-gate';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'unwritten';
UPDATE servers SET category = '🔒 Security' WHERE id = 'agent-audit-logger-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'agent-commerce-payments-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'agent-cost-allocator-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'agent-policy-enforcement-mcp';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'ai-gateway-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'ai-self-audit-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'blockchain-verification-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'dependency-updater-ai-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'dora-compliance-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'eu-ai-act-compliance-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'hr-management-ai-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'invoice-generator-ai-mcp';
UPDATE servers SET category = '💬 Communication' WHERE id = 'iso-27001-ai-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'iso-42001-ai-mcp';
UPDATE servers SET category = '💬 Communication' WHERE id = 'meok-bs7121-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'meok-eu-mobility-package-mcp';
UPDATE servers SET category = '💬 Communication' WHERE id = 'meok-ev-recall-transport-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'meok-tacho-audit-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mitre-atlas-mcp';
UPDATE servers SET category = '💬 Communication' WHERE id = 'notification-ai-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'pci-dss-mcp';
UPDATE servers SET category = '💬 Communication' WHERE id = 'regulatory-webhook-mcp';
UPDATE servers SET category = '🧠 Knowledge & Memory' WHERE id = 'vector-knowledge-graph-mcp';
UPDATE servers SET category = '💬 Communication' WHERE id = 'webhook-ai-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'interline';
UPDATE servers SET category = '🔒 Security' WHERE id = 'elephant-accountability-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'aeonos';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcp-server-62';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'coreason-ecosystem-federated-mcp-gateway';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'orcadub-mcp-server';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'convai-analytics';
UPDATE servers SET category = '🔒 Security' WHERE id = 'aeo-scanner';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'createya-ai-image-video-generation';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'crosspad-mcp';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'works-public-verifier';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'agent-skill';
UPDATE servers SET category = '🔒 Security' WHERE id = 'delego';
UPDATE servers SET category = '🔒 Security' WHERE id = 'fulcrum';
UPDATE servers SET category = '🔒 Security' WHERE id = 'fulcrum-2';
UPDATE servers SET category = '🔒 Security' WHERE id = 'contract-ops-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'sign-cli';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'gomodel';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'kta-oracle';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'ulink';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'ui-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'closeread-verify';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcp-bastion';
UPDATE servers SET category = '🔒 Security' WHERE id = 'checkmcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'greenlake-audit-logs-mcp';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'katana-markdown-linter';
UPDATE servers SET category = '🔒 Security' WHERE id = 'microsoft-project';
UPDATE servers SET category = '🔒 Security' WHERE id = 'horizun-pbi-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'proofflow';
UPDATE servers SET category = '🔒 Security' WHERE id = 'infinihash-kyt-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'lemonsqueezy-mcp-server';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'servicenow-mcp-ai';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'physbound';
UPDATE servers SET category = '🔒 Security' WHERE id = 'aisentinel-by-bizdnai';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'github-inside-claude-code';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'topos';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcp-198';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'servicenow-mcp-ai-2';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'mcp-hive-proxy';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'mpp32-mcp-server';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'mcp-plots';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'plots-mcp';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'vaults-diagram-tools';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'mcp-200';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'botverse';
UPDATE servers SET category = '🔒 Security' WHERE id = 'qnevt-verifiable-randomness-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'korg-ledger';
UPDATE servers SET category = '🔒 Security' WHERE id = 'url-safety-validator';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'composer';
UPDATE servers SET category = '🔒 Security' WHERE id = 'pagelens-ai';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'media-forge';
UPDATE servers SET category = '🔒 Security' WHERE id = 'vertaaux-mcp-2';
UPDATE servers SET category = '🔒 Security' WHERE id = 'audit-trail';
UPDATE servers SET category = '🔒 Security' WHERE id = 'pushary';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'mcp-202';
UPDATE servers SET category = '🔄 Version Control' WHERE id = 'quellgeist-commits';
UPDATE servers SET category = '🔒 Security' WHERE id = 'clawbackai-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'seracade';
UPDATE servers SET category = '🔒 Security' WHERE id = 'repo-test-architect';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'botopia-m2m-gateway';
UPDATE servers SET category = '🔒 Security' WHERE id = 'agent-audit-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'agentpay';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'agentpay-gateway-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'gatekeeper';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'ryvo-protocol';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'drawx-mcp-server';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'schematic';
UPDATE servers SET category = '🔒 Security' WHERE id = 'sentinelgate';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'agentic-pay';
UPDATE servers SET category = '🔒 Security' WHERE id = 'stackswap';
UPDATE servers SET category = '🔒 Security' WHERE id = 'catalyst-governance';
UPDATE servers SET category = '🔒 Security' WHERE id = 'iso27001-mcp';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'zephex';
UPDATE servers SET category = '📋 Product Management' WHERE id = 'nexus-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'thunder-compute';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'claude-code-conversation-search-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'trainzilla-coach-mcp';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'agirails-mcp-server';
UPDATE servers SET category = '🔒 Security' WHERE id = 'vorim-mcp-server';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'wayforth';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'wiring-diagram-mcp';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'brick-bacnet-mcp';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'agent-api-gateway';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'codepic';
UPDATE servers SET category = '💬 Communication' WHERE id = 'fastmcp-server-that-pages-on-call-via-100-notification-channels-apprise-wrappe';
UPDATE servers SET category = '🔎 Search & Data Extraction' WHERE id = 'quran-search-engine-mcp';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'agentic-mermaid';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'derived';
UPDATE servers SET category = '🔒 Security' WHERE id = 'librecrawl-technical-seo-audit-mcp-server';
UPDATE servers SET category = '🎓 Education' WHERE id = 'model-id-cheatsheet';
UPDATE servers SET category = '🔒 Security' WHERE id = 'aiseo-audit';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'agentic-reputation-gateway';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'agentgate';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'aimcpgate';
UPDATE servers SET category = '🔒 Security' WHERE id = 'healthclaw-guardrails';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'agentpay-2';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'trident';
UPDATE servers SET category = '📋 Product Management' WHERE id = 'alm-x-mcp-server';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'professional-invoice-generator';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'pdfapi-mcp-server';
UPDATE servers SET category = '💰 Finance & Fintech' WHERE id = 'clawvault-mcp-server';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'datoon';
UPDATE servers SET category = '📊 Monitoring' WHERE id = 'agentic-platform';
UPDATE servers SET category = '🔒 Security' WHERE id = 'gws-admin-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'mcp-threatintel';
UPDATE servers SET category = '🗄️ Databases' WHERE id = 'orm-mcp';
UPDATE servers SET category = '📊 Data Visualization' WHERE id = 'chalk';
UPDATE servers SET category = '🧠 Knowledge & Memory' WHERE id = 'mcp-audit';
UPDATE servers SET category = '🔒 Security' WHERE id = 'fake-star-audit-2';
UPDATE servers SET category = '🔒 Security' WHERE id = 'aribot';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'robokassa-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'aeo-mcp';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'maxion-mcp-gateway';
UPDATE servers SET category = '💬 Communication' WHERE id = '2captcha-mcp';
UPDATE servers SET category = '🔒 Security' WHERE id = 'har-forensics-mcp';
UPDATE servers SET category = '📂 Browser Automation' WHERE id = 'kshana-pnt-resilience-simulator';
UPDATE servers SET category = '🤖 Coding Agents' WHERE id = 'loki-mode';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'clawifi';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'yoauto-mcp';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'mcp-gateway-2';
UPDATE servers SET category = '☁️ Cloud Platforms' WHERE id = 'auxiliar-mcp-2';