import { getCloudflareContext } from '@opennextjs/cloudflare';
import { drizzle } from 'drizzle-orm/d1';
import { and, desc, eq } from 'drizzle-orm';
import { socialPosts } from '../../../db/schema';
import { escapeForXml, truncateToTwitterLimit } from '../../../lib/twitter';

export const dynamic = 'force-dynamic';

function toCdataSafe(value: string): string {
  return value.replace(/]]>/g, ']]]]><![CDATA[>');
}

export async function GET() {
  const siteUrl = 'https://allmcps.com';
  let items: Array<{
    guid: string;
    tweetText: string;
    createdAt: Date | null;
    serverId: string | null;
  }> = [];

  try {
    const ctx = await getCloudflareContext();
    if (ctx?.env?.DB) {
      const db = drizzle((ctx.env as any).DB);
      items = await db
        .select({
          guid: socialPosts.guid,
          tweetText: socialPosts.tweetText,
          createdAt: socialPosts.createdAt,
          serverId: socialPosts.serverId,
        })
        .from(socialPosts)
        .where(and(eq(socialPosts.channel, 'twitter'), eq(socialPosts.status, 'queued')))
        .orderBy(desc(socialPosts.createdAt))
        .limit(250);
    }
  } catch (error) {
    console.warn('Tweets RSS feed DB fetch failed.', error);
  }

  const rssItems = items
    .map((item) => {
      const pubDate = (item.createdAt ? new Date(item.createdAt) : new Date()).toUTCString();
      const itemUrl = item.serverId ? `${siteUrl}/mcp/${item.serverId}` : `${siteUrl}/tweets/rss.xml`;
      // Enforce X.com (280 char) limit for all items, including pre-existing ones in DB
      const tweetText = truncateToTwitterLimit(item.tweetText, 280);
      const title = tweetText.split('\n')[0] || 'Queued tweet';
      const encodedText = escapeForXml(tweetText);
      return `    <item>
      <title>${escapeForXml(title)}</title>
      <link>${itemUrl}</link>
      <guid isPermaLink="false">${escapeForXml(item.guid)}</guid>
      <pubDate>${pubDate}</pubDate>
      <description>${encodedText}</description>
      <content:encoded><![CDATA[${toCdataSafe(tweetText)}]]></content:encoded>
    </item>`;
    })
    .join('\n');

  const xml = `<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
<channel>
  <title>AllMCPs Tweet Queue</title>
  <link>${siteUrl}/tweets/rss.xml</link>
  <description>Queued AllMCPs tweets generated by cron and listing approvals.</description>
  <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
${rssItems}
</channel>
</rss>`;

  return new Response(xml, {
    headers: {
      'Content-Type': 'application/rss+xml; charset=utf-8',
      'Cache-Control': 'public, max-age=60, s-maxage=300',
    },
  });
}
