import { getCloudflareContext } from '@opennextjs/cloudflare';
import { and, desc, eq, gt } from 'drizzle-orm';
import { drizzle } from 'drizzle-orm/d1';
import { socialPosts } from '../../../db/schema';
import {
  dedupeTweetItems,
  escapeForXml,
  TWITTER_SAFE_CHAR_LIMIT,
  truncateToTwitterLimit,
} from '../../../lib/twitter';

export const dynamic = 'force-dynamic';

// Queued items older than this (in days) are considered stale and excluded from the active feed
const MAX_FEED_AGE_DAYS = 14;

function toCdataSafe(value: string): string {
  return value.replace(/]]>/g, ']]]]><![CDATA[>');
}

export async function GET() {
  const siteUrl = 'https://allmcps.com';
  let items: Array<{
    guid: string;
    tweetText: string;
    createdAt: Date | null;
    serverId: string | null;
  }> = [];

  try {
    const ctx = await getCloudflareContext();
    if (ctx?.env?.DB) {
      const db = drizzle((ctx.env as any).DB);
      const staleCutoff = new Date(
        Date.now() - MAX_FEED_AGE_DAYS * 24 * 60 * 60 * 1000,
      );
      items = await db
        .select({
          guid: socialPosts.guid,
          tweetText: socialPosts.tweetText,
          createdAt: socialPosts.createdAt,
          serverId: socialPosts.serverId,
        })
        .from(socialPosts)
        .where(
          and(
            eq(socialPosts.channel, 'twitter'),
            eq(socialPosts.status, 'queued'),
            gt(socialPosts.createdAt, staleCutoff),
          ),
        )
        .orderBy(desc(socialPosts.createdAt))
        .limit(100);
    }
  } catch (error) {
    console.warn('Tweets RSS feed DB fetch failed.', error);
  }

  // Collapse duplicate bodies and duplicate servers before rendering.
  // Items arrive newest-first, keeping the most recent copy of each unique tweet and server.
  const dedupedItems = dedupeTweetItems(items);

  const rssItems = dedupedItems
    .map((item) => {
      const pubDate = (
        item.createdAt ? new Date(item.createdAt) : new Date()
      ).toUTCString();
      const itemUrl = item.serverId
        ? `${siteUrl}/mcp/${item.serverId}`
        : `${siteUrl}/tweets/rss.xml`;
      // Enforce a safe character limit (below X.com's 280 hard cap) for every
      // item — including pre-existing rows in the DB — so downstream schedulers
      // (Buffer via make.com) never reject a post for length. Because this feed
      // is rebuilt on every request, the ceiling applies to all current and
      // future entries regardless of what was stored.
      const tweetText = truncateToTwitterLimit(
        item.tweetText,
        TWITTER_SAFE_CHAR_LIMIT,
      );
      const title = tweetText.split('\n')[0] || 'Queued tweet';
      const encodedText = escapeForXml(tweetText);
      return `    <item>
      <title>${escapeForXml(title)}</title>
      <link>${itemUrl}</link>
      <guid isPermaLink="false">${escapeForXml(item.guid)}</guid>
      <pubDate>${pubDate}</pubDate>
      <description>${encodedText}</description>
      <content:encoded><![CDATA[${toCdataSafe(tweetText)}]]></content:encoded>
    </item>`;
    })
    .join('\n');

  const xml = `<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
<channel>
  <title>AllMCPs Tweet Queue</title>
  <link>${siteUrl}/tweets/rss.xml</link>
  <description>Queued AllMCPs tweets generated by cron and listing approvals.</description>
  <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
${rssItems}
</channel>
</rss>`;

  return new Response(xml, {
    headers: {
      'Content-Type': 'application/rss+xml; charset=utf-8',
      'Cache-Control': 'public, max-age=60, s-maxage=300',
    },
  });
}
